language: objective-c
osx_image: xcode9

env:
  global:
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8
    - XCODE_WORKSPACE=AlamofireObjectMapper.xcworkspace
  matrix:
    - SCHEME="AlamofireObjectMapper iOS"
    - SCHEME="AlamofireObjectMapper OSX"
    - SCHEME="AlamofireObjectMapper tvOS"

before_install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
  - set -o pipefail
  - xcodebuild -workspace "$XCODE_WORKSPACE" -scheme "$SCHEME" -configuration Debug clean build CODE_SIGN_IDENTITY="" BITCODE_GENERATION_MODE=marker CODE_SIGNING_REQUIRED=NO | xcpretty -c;
  - xcodebuild -workspace "$XCODE_WORKSPACE" -scheme "$SCHEME" -configuration Release clean build CODE_SIGN_IDENTITY="" BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO | xcpretty -c;

notifications:
  email: false